name: .net framework CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .net framework env
        uses: vrnobody/Setup-DotNetFrameworkEnv@v1

      - name: Restore Nuget packages
        run: nuget restore MyProject.sln

      - name: Build solution
        run: msbuild src/slowTriangles.sln -p:Configuration=Release

      - name: Run unit tests
        run: |
          function Invoke-VSTest {
            & "vstest.console.exe" $args
            if(-not $?){ throw "fail!" }
          }
          Invoke-VSTest "src/test/bin/Release/test.dll"
